services:
  - type: web
    name: zyra-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

  - type: static
    name: zyra-frontend
    plan: free
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0